In [51]:
# weather_1=pd.read_csv('../Datasets/hourly_dataframe.csv',index_col=False)
# weather_2=pd.read_csv('../Datasets/hourly_dataframe_final.csv',index_col=False)

# weather_total_df=pd.concat([weather_1,weather_2]).drop_duplicates()
# weather_total_df.to_csv('../Datasets/hourly_weather_data_complete.csv',index=False)

In [52]:
import pandas as pd

In [53]:
hourly_weather=pd.read_csv('../Datasets/hourly_weather_data_complete.csv',index_col=False)
hourly_weather['acq_date']=pd.to_datetime(hourly_weather['date']).dt.date
hourly_weather['time']=pd.to_datetime(hourly_weather['date']).dt.time
hourly_weather

,date,latitude,longitude,temperature_2m,relative_humidity_2m,dew_point_2m,apparent_temperature,precipitation,rain,snowfall,...,soil_temperature_0_to_7cm,soil_temperature_7_to_28cm,soil_temperature_28_to_100cm,soil_temperature_100_to_255cm,soil_moisture_0_to_7cm,soil_moisture_7_to_28cm,soil_moisture_28_to_100cm,soil_moisture_100_to_255cm,acq_date,time
0,2020-01-02 07:00:00+00:00,33.77762,-118.22819,10.910,95.444640,10.210,9.915919,0.0,0.0,0.0,...,11.360001,13.410000,13.960000,21.910,0.274,0.319,0.195,0.026,2020-01-02,07:00:00
1,2020-01-02 08:00:00+00:00,33.77762,-118.22819,11.010,96.407850,10.460,9.846991,0.0,0.0,0.0,...,11.060000,13.260000,14.010000,21.910,0.275,0.319,0.195,0.026,2020-01-02,08:00:00
2,2020-01-02 09:00:00+00:00,33.77762,-118.22819,10.460,95.428820,9.760,9.326071,0.0,0.0,0.0,...,10.760000,13.110001,14.010000,21.910,0.275,0.318,0.195,0.026,2020-01-02,09:00:00
3,2020-01-02 10:00:00+00:00,33.77762,-118.22819,10.160,95.739235,9.510,9.024604,0.0,0.0,0.0,...,10.360001,12.960000,14.010000,21.910,0.276,0.318,0.195,0.026,2020-01-02,10:00:00
4,2020-01-02 11:00:00+00:00,33.77762,-118.22819,9.010,97.006090,8.560,7.496633,0.0,0.0,0.0,...,9.960000,12.810000,14.010000,21.910,0.276,0.318,0.195,0.026,2020-01-02,11:00:00
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1449955,2024-09-02 02:00:00+00:00,35.03100,-118.31759,31.249,16.880789,3.199,27.736122,0.0,0.0,0.0,...,38.249000,31.598999,28.549000,25.549,0.022,0.149,0.213,0.187,2024-09-02,02:00:00
1449956,2024-09-02 03:00:00+00:00,35.03100,-118.31759,28.699,18.999668,2.799,24.775993,0.0,0.0,0.0,...,35.499000,31.699000,28.549000,25.549,0.022,0.149,0.213,0.187,2024-09-02,03:00:00
1449957,2024-09-02 04:00:00+00:00,35.03100,-118.31759,27.449,20.800364,3.049,23.649523,0.0,0.0,0.0,...,33.149000,31.699000,28.549000,25.549,0.022,0.149,0.213,0.187,2024-09-02,04:00:00
1449958,2024-09-02 05:00:00+00:00,35.03100,-118.31759,26.949,21.495300,3.099,23.265472,0.0,0.0,0.0,...,31.199000,31.699000,28.598999,25.549,0.022,0.149,0.213,0.187,2024-09-02,05:00:00
1449959,2024-09-02 06:00:00+00:00,35.03100,-118.31759,26.299,22.334295,3.099,22.471298,0.0,0.0,0.0,...,29.649000,31.598999,28.598999,25.549,0.022,0.149,0.213,0.187,2024-09-02,06:00:00

In [54]:
wildfire_df=pd.read_csv('../Datasets/wildfire_df.csv')
wildfire_df=wildfire_df[(wildfire_df['state']=='California') & (wildfire_df['acq_date']>'2020-01-01') & 
                        (wildfire_df['latitude']<=36)].copy()
# Dropping rows where same day and same time there were multiple rows
wildfire_df.dropna(subset=['acq_time','acq_date'],inplace=True)

# fixing and typecasting date and time column  properly
wildfire_df['acq_date']=pd.to_datetime(wildfire_df['acq_date']).dt.date
wildfire_df['acq_time'] = wildfire_df['acq_time'].astype(str).str.zfill(4)  # Ensure leading zeros for hours < 10
wildfire_df['acq_time'] = pd.to_datetime(wildfire_df['acq_time'], format='%H%M').dt.time
wildfire_df['acq_time']= pd.to_datetime(wildfire_df['acq_time'], format='%H:%M:%S')
wildfire_df['nearest_hour']=wildfire_df['acq_time'].dt.round('H').dt.time
wildfire_df['acq_time']=wildfire_df['acq_time'].dt.time
wildfire_df

C:\Users\Olan\AppData\Local\Temp\ipykernel_36468\232376858.py:1: DtypeWarning: Columns (10) have mixed types. Specify dtype option on import or set low_memory=False.
  wildfire_df=pd.read_csv('../Datasets/wildfire_df.csv')

,latitude,longitude,bright_ti4,scan,track,acq_date,acq_time,satellite,instrument,confidence,version,bright_ti5,frp,daynight,type,state,nearest_hour
5276400,33.77762,-118.22819,297.45,0.42,0.61,2020-01-02,08:53:00,N,VIIRS,n,2,283.34,1.14,N,0.0,California,09:00:00
5276401,33.77818,-118.23756,298.90,0.42,0.61,2020-01-02,08:53:00,N,VIIRS,n,2,285.94,1.01,N,0.0,California,09:00:00
5276402,33.81285,-118.23906,297.82,0.42,0.61,2020-01-02,08:53:00,N,VIIRS,n,2,285.95,0.99,N,0.0,California,09:00:00
5276403,33.81887,-118.24325,296.60,0.42,0.61,2020-01-02,08:53:00,N,VIIRS,n,2,285.98,1.08,N,2.0,California,09:00:00
5276404,33.81951,-118.24489,298.51,0.42,0.61,2020-01-02,08:53:00,N,VIIRS,n,2,286.40,0.92,N,2.0,California,09:00:00
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
8054566,34.32040,-118.51376,301.29,0.39,0.44,2024-09-01,09:20:00,N21,VIIRS,n,2.0NRT,290.06,0.39,N,0.0,California,09:00:00
8054567,34.33338,-118.52016,311.39,0.39,0.44,2024-09-01,09:20:00,N21,VIIRS,n,2.0NRT,290.80,1.18,N,0.0,California,09:00:00
8054568,34.42942,-118.64478,311.10,0.40,0.44,2024-09-01,09:20:00,N21,VIIRS,n,2.0NRT,290.99,1.34,N,0.0,California,09:00:00
8054569,34.60736,-117.33656,317.76,0.52,0.42,2024-09-01,09:20:00,N21,VIIRS,n,2.0NRT,295.19,3.13,N,0.0,California,09:00:00
8054571,35.03100,-118.31759,305.78,0.39,0.44,2024-09-01,09:20:00,N21,VIIRS,n,2.0NRT,294.11,1.17,N,0.0,California,09:00:00

In [55]:
wildfire_df=wildfire_df.merge(hourly_weather,left_on=['latitude','longitude','acq_date','nearest_hour'],right_on=['latitude','longitude','acq_date','time'],how='left').drop_duplicates()

In [59]:
# Dropping instances where time is NaN - Data was not available in the meteostat api
wildfire_df.dropna(subset=['time'],inplace=True)

In [64]:
wildfire_df.to_csv('../Datasets/raw_final_df.csv',index=False)